"""initial schema

Revision ID: 6e9d9650ac5e
Revises: 
Create Date: 2026-05-01 02:44:47.212488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e9d9650ac5e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('size', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('breed', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('shortDescription', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('longDescription', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('goodWithKids', sa.Boolean(), nullable=False),
    sa.Column('goodWithDogs', sa.Boolean(), nullable=False),
    sa.Column('homeTrained', sa.Boolean(), nullable=False),
    sa.Column('availableForAdoption', sa.Enum('available', 'pending', 'adopted', name='animalstatus'), nullable=False),
    sa.Column('media', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_name'), 'animal', ['name'], unique=False)
    op.create_index(op.f('ix_animal_type'), 'animal', ['type'], unique=False)
    op.create_table('contactmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('lastName', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pawuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('lastName', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pawuser_email'), 'pawuser', ['email'], unique=True)
    op.create_table('shelter_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shelter_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('shelter_email', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('shelter_phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('shelter_address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('zip_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('lastName', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('availability', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('availableDays', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('areasOfInterest', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('whyVolunteer', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('specialSkills', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('emergencyContactName', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('emergencyContactPhone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='volunteerstatus'), nullable=False),
    sa.Column('privacyAgreement', sa.Boolean(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volunteer_email'), 'volunteer', ['email'], unique=True)
    op.create_index(op.f('ix_volunteer_id'), 'volunteer', ['id'], unique=True)
    op.create_table('adoptionapplication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animalId', sa.Integer(), nullable=False),
    sa.Column('applicantName', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('applicantLastName', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('zipCode', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('birthdate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('occupation', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('reasonForAdoption', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('experienceWithPets', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('homeType', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('whoLivesInHouse', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('agreeToTerms', sa.Boolean(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('approved', 'pending', 'rejected', name='adoptionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['animalId'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adoptionapplication_animalId'), 'adoptionapplication', ['animalId'], unique=False)
    op.create_index(op.f('ix_adoptionapplication_id'), 'adoptionapplication', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adoptionapplication_id'), table_name='adoptionapplication')
    op.drop_index(op.f('ix_adoptionapplication_animalId'), table_name='adoptionapplication')
    op.drop_table('adoptionapplication')
    op.drop_index(op.f('ix_volunteer_id'), table_name='volunteer')
    op.drop_index(op.f('ix_volunteer_email'), table_name='volunteer')
    op.drop_table('volunteer')
    op.drop_table('subscription')
    op.drop_table('shelter_settings')
    op.drop_index(op.f('ix_pawuser_email'), table_name='pawuser')
    op.drop_table('pawuser')
    op.drop_table('contactmessage')
    op.drop_index(op.f('ix_animal_type'), table_name='animal')
    op.drop_index(op.f('ix_animal_name'), table_name='animal')
    op.drop_table('animal')
    # ### end Alembic commands ###
